---
- name: Send conf file jinja
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: Restart Nginx
    
- name: Create certificate directory
  file:
    path: /etc/nginx/ssl
    state: directory

- name: Copy certificate files
  copy:
    src: ../../../ssl/{{ item }}
    dest: /etc/nginx/ssl/
  with_items:
    - nginx.key
    - nginx.crt