- name: Deploy Files
  hosts: deployment1
  tasks:
    - name: Delete contents of a directory
      ansible.builtin.file:
        path: /home/s1/deployment
        state: absent
        recurse: yes
      become: yes
    - name: Copy files
      ansible.builtin.copy:
        src: .
        dest: /home/s1/deployment/
      become: yes
  