---
- name: open port 80 
  firewalld:
    zone: public
    port: 80/tcp
    permanent: true
    state: enabled
- name: open port 443
  firewalld:
    zone: public
    port: 443/tcp
    permanent: true
    state: enabled