---
- name: Provision pkgs for infra. (Docker, Docker-Compose, NGINX)
  hosts: deployment_servers
  become: true
  roles:
    - install_dockerce
    - add_docker_user
    - install_docker_compose
    - install_nginx
    - config_nginx
    - config_firewall