---
- name: "Downloading docker-compose binaries"
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-darwin-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'