---
- name: "Installing Nginx Prerequisite packages"
  yum:
    name: ['epel-release']
    state: latest
- name: "Install Nginx"
  yum:
    name: nginx
    state: latest
    update_cache: yes